apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coredns.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- if .Values.isClusterService }}
    k8s-app: {{ .Chart.Name | quote }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    {{- end }}
    app.kubernetes.io/name: {{ template "coredns.name" . }}
data:
  Corefile: |-
    .:53 {
{{ .Values.preConfigBlock | indent 8 }}
        etcd {{ .Values.internalZone| default "." }} {
            path /skydns
            endpoint http://{{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.cluster.local:2379
        }
      {{- if .Values.prometheus.service.enabled }}
        prometheus 0.0.0.0:9153
      {{- end }}
        forward .{{ range .Values.forwardingServers }} {{ . }}{{ end }}
{{ .Values.postConfigBlock | indent 8 }}
    }
