etcd:
  auth:
    rbac:
      enabled: false
  allowNoneAuthentication: true
  persistence:
    enabled: false
external-dns:
  provider: coredns
  coredns:
    # XXX - due to the current design, the user has to hook this up themselves
    # Helm has no intention of making this fixable without completely redesigning the chart:
    # https://github.com/helm/helm/issues/2492
    # https://github.com/helm/helm/pull/3252
    etcdEndpoints: "http://RELEASE_NAME-etcd.NAMESPACE.svc.cluster.local:2379"
  triggerLoopOnEvent: true
  policy: sync
  registry: noop
