coredns:
  image:
    repository: coredns/coredns
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceType: "LoadBalancer"
  prometheus:
    monitor:
      enabled: true # might need to be false to install before the operator is available?
  service:
    loadBalancerIP: "192.168.42.53" ## TODO: move this one out to stubernetes-system

  serviceAccount:
    create: false

  rbac:
    create: false

  isClusterService: false
  priorityClassName: ""

  servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
      configBlock: |-
        lameduck 5s
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    # serves our internal names
    - name: etcd
      parameters: internal
      configBlock: |- # TODO: parameterize this service URL
        path /skydns
        endpoint http://household-skydns-etcd.household-system.svc.cluster.local:2379
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    # Forwards to encrypted connections
    # TODO: expand these to include secondaries?
    - name: forward
      parameters: . tls://1.1.1.1 tls://9.9.9.10 tls://8.8.8.8
    - name: cache
      parameters: 30
    - name: loop
    - name: reload
    - name: loadbalance
