apiVersion: v2
name: coredns
version: 1.13.0
appVersion: 1.6.9
description: inhouse-dns CoreDNS subchart (forked from stable/coredns 1.13.0)
keywords:
- coredns
- dns
- kubedns
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
